name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Pack app with Pyinstaller:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: PyInstaller-release
        path: | 
          src/dist/windows
          src/config.ini
  Compile app with nuitka:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install nuitka
    - name: Run compilation
      run: |
        python -m nuitka --onefile src/main.py
    - uses: actions/upload-artifact@v3
      with:
        name: Nuitka-release
        path: | 
          main.dist/
          src/config.ini
    

