name: Build app

on:
  push:
    branches: [ main ]
    paths:
    - '**.py'
  pull_request:
    branches: [ main ]

jobs:
  Pack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: PyInstaller-release
        path: | 
          src/dist/windows
          src/config.ini